import 'package:flutter/material.dart';

import '../models/furniture_item.dart';

enum FurnitureCategory {
  sleep, seating, tables, storage, media, kitchen, bathroom, lighting, decor, outdoor, office
}

class FurnitureCatalogEntry {
  final String id;
  final FurnitureType type;
  final String label;
  final FurnitureCategory category;
  final IconData icon;
  final double defaultWidthFt;
  final double defaultLengthFt;
  final String description;

  const FurnitureCatalogEntry({
    required this.id,
    required this.type,
    required this.label,
    required this.category,
    required this.icon,
    required this.defaultWidthFt,
    required this.defaultLengthFt,
    required this.description,
  });
}

/// Built-in furniture definitions (top-down sizes in feet).
/// ~248 consumer planner SKUs — variants share [FurnitureType] for painters.
class FurnitureCatalog {
  static const List<FurnitureCatalogEntry> all = [
    FurnitureCatalogEntry(
      id: 'twin_bed',
      type: FurnitureType.bed,
      label: 'Twin bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 3.2,
      defaultLengthFt: 6.3,
      description: 'Single / twin mattress',
    ),
    FurnitureCatalogEntry(
      id: 'full_bed',
      type: FurnitureType.bed,
      label: 'Full bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 4.5,
      defaultLengthFt: 6.3,
      description: 'Full / double',
    ),
    FurnitureCatalogEntry(
      id: 'queen_bed',
      type: FurnitureType.bed,
      label: 'Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 5.0,
      defaultLengthFt: 6.7,
      description: 'Queen-size bed',
    ),
    FurnitureCatalogEntry(
      id: 'king_bed',
      type: FurnitureType.bed,
      label: 'King bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 6.3,
      defaultLengthFt: 6.7,
      description: 'King-size bed',
    ),
    FurnitureCatalogEntry(
      id: 'cal_king_bed',
      type: FurnitureType.bed,
      label: 'California king',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 6.0,
      defaultLengthFt: 7.0,
      description: 'Cal king mattress',
    ),
    FurnitureCatalogEntry(
      id: 'bunk_bed',
      type: FurnitureType.bed,
      label: 'Bunk bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 3.5,
      defaultLengthFt: 6.5,
      description: 'Twin bunk footprint',
    ),
    FurnitureCatalogEntry(
      id: 'daybed',
      type: FurnitureType.bed,
      label: 'Daybed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 3.5,
      defaultLengthFt: 6.5,
      description: 'Sofa-style daybed',
    ),
    FurnitureCatalogEntry(
      id: 'crib',
      type: FurnitureType.bed,
      label: 'Crib',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 2.5,
      defaultLengthFt: 4.5,
      description: 'Baby crib',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand',
      type: FurnitureType.nightstand,
      label: 'Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Bedside table',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_wide',
      type: FurnitureType.nightstand,
      label: 'Wide nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 2.0,
      defaultLengthFt: 1.6,
      description: 'Larger bedside',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_pair',
      type: FurnitureType.nightstand,
      label: 'Nightstand (pair mark)',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Single of pair',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3',
      type: FurnitureType.sofa,
      label: 'Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 7.0,
      defaultLengthFt: 3.0,
      description: 'Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_2',
      type: FurnitureType.sofa,
      label: 'Loveseat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 5.0,
      defaultLengthFt: 3.0,
      description: '2-seater sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sectional',
      type: FurnitureType.sofa,
      label: 'Sectional (L)',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 8.5,
      defaultLengthFt: 6.5,
      description: 'L-shaped sectional footprint',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_chaise',
      type: FurnitureType.sofa,
      label: 'Sofa + chaise',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 8.0,
      defaultLengthFt: 5.5,
      description: 'Sofa with chaise',
    ),
    FurnitureCatalogEntry(
      id: 'recliner',
      type: FurnitureType.chair,
      label: 'Recliner',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 3.0,
      defaultLengthFt: 3.2,
      description: 'Reclining lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'armchair',
      type: FurnitureType.chair,
      label: 'Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 2.8,
      defaultLengthFt: 2.8,
      description: 'Lounge armchair',
    ),
    FurnitureCatalogEntry(
      id: 'dining_chair',
      type: FurnitureType.chair,
      label: 'Dining chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 1.6,
      defaultLengthFt: 1.6,
      description: 'Dining chair',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair',
      type: FurnitureType.chair,
      label: 'Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 2.0,
      defaultLengthFt: 2.0,
      description: 'Desk chair',
    ),
    FurnitureCatalogEntry(
      id: 'stool',
      type: FurnitureType.chair,
      label: 'Stool',
      category: FurnitureCategory.seating,
      icon: Icons.event_seat,
      defaultWidthFt: 1.2,
      defaultLengthFt: 1.2,
      description: 'Bar / side stool',
    ),
    FurnitureCatalogEntry(
      id: 'ottoman',
      type: FurnitureType.chair,
      label: 'Ottoman',
      category: FurnitureCategory.seating,
      icon: Icons.crop_square,
      defaultWidthFt: 2.0,
      defaultLengthFt: 2.0,
      description: 'Footstool / ottoman',
    ),
    FurnitureCatalogEntry(
      id: 'bench',
      type: FurnitureType.chair,
      label: 'Bench',
      category: FurnitureCategory.seating,
      icon: Icons.weekend_outlined,
      defaultWidthFt: 4.0,
      defaultLengthFt: 1.5,
      description: 'Entry or dining bench',
    ),
    FurnitureCatalogEntry(
      id: 'bean_bag',
      type: FurnitureType.chair,
      label: 'Bean bag',
      category: FurnitureCategory.seating,
      icon: Icons.circle,
      defaultWidthFt: 3.0,
      defaultLengthFt: 3.0,
      description: 'Floor lounge seat',
    ),
    FurnitureCatalogEntry(
      id: 'bar_stool',
      type: FurnitureType.chair,
      label: 'Bar stool',
      category: FurnitureCategory.seating,
      icon: Icons.event_seat,
      defaultWidthFt: 1.4,
      defaultLengthFt: 1.4,
      description: 'Counter stool',
    ),
    FurnitureCatalogEntry(
      id: 'gaming_chair',
      type: FurnitureType.chair,
      label: 'Gaming chair',
      category: FurnitureCategory.seating,
      icon: Icons.sports_esports,
      defaultWidthFt: 2.2,
      defaultLengthFt: 2.2,
      description: 'Racing-style chair',
    ),
    FurnitureCatalogEntry(
      id: 'coffee_table',
      type: FurnitureType.table,
      label: 'Coffee table',
      category: FurnitureCategory.tables,
      icon: Icons.table_bar,
      defaultWidthFt: 3.5,
      defaultLengthFt: 2.0,
      description: 'Living room coffee table',
    ),
    FurnitureCatalogEntry(
      id: 'coffee_table_round',
      type: FurnitureType.table,
      label: 'Round coffee table',
      category: FurnitureCategory.tables,
      icon: Icons.table_bar,
      defaultWidthFt: 3.0,
      defaultLengthFt: 3.0,
      description: 'Round coffee table',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4',
      type: FurnitureType.table,
      label: 'Dining table (4)',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 4.0,
      defaultLengthFt: 3.0,
      description: '4-person dining',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_6',
      type: FurnitureType.table,
      label: 'Dining table (6)',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 5.5,
      defaultLengthFt: 3.2,
      description: '6-person dining',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_8',
      type: FurnitureType.table,
      label: 'Dining table (8)',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 7.0,
      defaultLengthFt: 3.5,
      description: '8-person dining',
    ),
    FurnitureCatalogEntry(
      id: 'desk',
      type: FurnitureType.desk,
      label: 'Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 4.5,
      defaultLengthFt: 2.2,
      description: 'Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_small',
      type: FurnitureType.desk,
      label: 'Compact desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 3.5,
      defaultLengthFt: 1.8,
      description: 'Small writing desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_l',
      type: FurnitureType.desk,
      label: 'L-desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 5.5,
      defaultLengthFt: 4.5,
      description: 'Corner L-desk footprint',
    ),
    FurnitureCatalogEntry(
      id: 'standing_desk',
      type: FurnitureType.desk,
      label: 'Standing desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 4.5,
      defaultLengthFt: 2.4,
      description: 'Sit-stand desk',
    ),
    FurnitureCatalogEntry(
      id: 'side_table',
      type: FurnitureType.table,
      label: 'Side table',
      category: FurnitureCategory.tables,
      icon: Icons.table_bar,
      defaultWidthFt: 1.8,
      defaultLengthFt: 1.8,
      description: 'End / side table',
    ),
    FurnitureCatalogEntry(
      id: 'console_table',
      type: FurnitureType.table,
      label: 'Console table',
      category: FurnitureCategory.tables,
      icon: Icons.table_bar,
      defaultWidthFt: 4.0,
      defaultLengthFt: 1.2,
      description: 'Hall console',
    ),
    FurnitureCatalogEntry(
      id: 'nesting_tables',
      type: FurnitureType.table,
      label: 'Nesting tables',
      category: FurnitureCategory.tables,
      icon: Icons.table_bar,
      defaultWidthFt: 2.0,
      defaultLengthFt: 1.5,
      description: 'Set of nesting tables',
    ),
    FurnitureCatalogEntry(
      id: 'picnic_table',
      type: FurnitureType.outdoor,
      label: 'Picnic table',
      category: FurnitureCategory.outdoor,
      icon: Icons.table_restaurant,
      defaultWidthFt: 6.0,
      defaultLengthFt: 3.0,
      description: 'Outdoor picnic table',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe',
      type: FurnitureType.wardrobe,
      label: 'Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 6.5,
      defaultLengthFt: 1.5,
      description: 'Closet / sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_wide',
      type: FurnitureType.wardrobe,
      label: 'Wide wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 6.7,
      defaultLengthFt: 1.5,
      description: 'Large sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_narrow',
      type: FurnitureType.wardrobe,
      label: 'Narrow wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.8,
      description: 'Single wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'dresser',
      type: FurnitureType.dresser,
      label: 'Dresser',
      category: FurnitureCategory.storage,
      icon: Icons.inventory_2,
      defaultWidthFt: 4.5,
      defaultLengthFt: 1.8,
      description: 'Chest of drawers',
    ),
    FurnitureCatalogEntry(
      id: 'chest',
      type: FurnitureType.dresser,
      label: 'Tall chest',
      category: FurnitureCategory.storage,
      icon: Icons.inventory_2,
      defaultWidthFt: 2.5,
      defaultLengthFt: 1.6,
      description: 'Tall dresser',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf',
      type: FurnitureType.bookshelf,
      label: 'Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.0,
      description: 'Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_tall',
      type: FurnitureType.bookshelf,
      label: 'Tall bookcase',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 2.5,
      defaultLengthFt: 1.2,
      description: 'Tall narrow bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'shelf_low',
      type: FurnitureType.bookshelf,
      label: 'Low shelf',
      category: FurnitureCategory.storage,
      icon: Icons.view_agenda,
      defaultWidthFt: 4.0,
      defaultLengthFt: 1.2,
      description: 'Low media / display shelf',
    ),
    FurnitureCatalogEntry(
      id: 'cabinet',
      type: FurnitureType.wardrobe,
      label: 'Storage cabinet',
      category: FurnitureCategory.storage,
      icon: Icons.kitchen,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.5,
      description: 'General cabinet',
    ),
    FurnitureCatalogEntry(
      id: 'shoe_rack',
      type: FurnitureType.bookshelf,
      label: 'Shoe rack',
      category: FurnitureCategory.storage,
      icon: Icons.grid_view,
      defaultWidthFt: 2.5,
      defaultLengthFt: 1.0,
      description: 'Entry shoe storage',
    ),
    FurnitureCatalogEntry(
      id: 'filing_cabinet',
      type: FurnitureType.dresser,
      label: 'Filing cabinet',
      category: FurnitureCategory.storage,
      icon: Icons.folder,
      defaultWidthFt: 1.5,
      defaultLengthFt: 2.0,
      description: 'Office file cabinet',
    ),
    FurnitureCatalogEntry(
      id: 'sideboard',
      type: FurnitureType.wardrobe,
      label: 'Sideboard',
      category: FurnitureCategory.storage,
      icon: Icons.inventory_2,
      defaultWidthFt: 5.5,
      defaultLengthFt: 1.6,
      description: 'Dining sideboard',
    ),
    FurnitureCatalogEntry(
      id: 'closet_walkin',
      type: FurnitureType.wardrobe,
      label: 'Walk-in zone',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 6.0,
      defaultLengthFt: 5.0,
      description: 'Walk-in closet footprint',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit',
      type: FurnitureType.tvUnit,
      label: 'TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 5.0,
      defaultLengthFt: 1.5,
      description: 'TV stand / media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_wide',
      type: FurnitureType.tvUnit,
      label: 'Wide TV console',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 6.5,
      defaultLengthFt: 1.6,
      description: 'Large media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_compact',
      type: FurnitureType.tvUnit,
      label: 'Compact TV stand',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 3.5,
      defaultLengthFt: 1.4,
      description: 'Small TV stand',
    ),
    FurnitureCatalogEntry(
      id: 'media_tower',
      type: FurnitureType.tvUnit,
      label: 'Media tower',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 2.0,
      defaultLengthFt: 1.5,
      description: 'Tall media tower',
    ),
    FurnitureCatalogEntry(
      id: 'soundbar_mark',
      type: FurnitureType.tvUnit,
      label: 'Soundbar zone',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 4.0,
      defaultLengthFt: 0.8,
      description: 'Soundbar / speaker mark',
    ),
    FurnitureCatalogEntry(
      id: 'projector_screen',
      type: FurnitureType.tvUnit,
      label: 'Projector screen',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 8.0,
      defaultLengthFt: 0.5,
      description: 'Screen wall mark',
    ),
    FurnitureCatalogEntry(
      id: 'fridge',
      type: FurnitureType.appliance,
      label: 'Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 3.0,
      defaultLengthFt: 2.8,
      description: 'Full-size fridge',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_mini',
      type: FurnitureType.appliance,
      label: 'Mini fridge',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 1.8,
      defaultLengthFt: 1.8,
      description: 'Compact fridge',
    ),
    FurnitureCatalogEntry(
      id: 'stove',
      type: FurnitureType.appliance,
      label: 'Range / stove',
      category: FurnitureCategory.kitchen,
      icon: Icons.local_fire_department,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Cooktop + oven',
    ),
    FurnitureCatalogEntry(
      id: 'dishwasher',
      type: FurnitureType.appliance,
      label: 'Dishwasher',
      category: FurnitureCategory.kitchen,
      icon: Icons.countertops,
      defaultWidthFt: 2.0,
      defaultLengthFt: 2.2,
      description: 'Built-in dishwasher',
    ),
    FurnitureCatalogEntry(
      id: 'kitchen_island',
      type: FurnitureType.table,
      label: 'Kitchen island',
      category: FurnitureCategory.kitchen,
      icon: Icons.countertops,
      defaultWidthFt: 6.0,
      defaultLengthFt: 3.0,
      description: 'Island with seating',
    ),
    FurnitureCatalogEntry(
      id: 'kitchen_counter',
      type: FurnitureType.table,
      label: 'Counter run',
      category: FurnitureCategory.kitchen,
      icon: Icons.countertops,
      defaultWidthFt: 8.0,
      defaultLengthFt: 2.0,
      description: 'Counter footprint',
    ),
    FurnitureCatalogEntry(
      id: 'microwave_cart',
      type: FurnitureType.table,
      label: 'Microwave cart',
      category: FurnitureCategory.kitchen,
      icon: Icons.microwave,
      defaultWidthFt: 2.0,
      defaultLengthFt: 1.5,
      description: 'Appliance cart',
    ),
    FurnitureCatalogEntry(
      id: 'pantry',
      type: FurnitureType.wardrobe,
      label: 'Pantry cabinet',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.0,
      description: 'Tall pantry',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub',
      type: FurnitureType.bathtub,
      label: 'Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 5.0,
      defaultLengthFt: 2.8,
      description: 'Standard tub',
    ),
    FurnitureCatalogEntry(
      id: 'shower_stall',
      type: FurnitureType.bathtub,
      label: 'Shower stall',
      category: FurnitureCategory.bathroom,
      icon: Icons.shower,
      defaultWidthFt: 3.0,
      defaultLengthFt: 3.0,
      description: 'Walk-in shower',
    ),
    FurnitureCatalogEntry(
      id: 'toilet',
      type: FurnitureType.toilet,
      label: 'Toilet',
      category: FurnitureCategory.bathroom,
      icon: Icons.wc,
      defaultWidthFt: 1.5,
      defaultLengthFt: 2.5,
      description: 'Toilet footprint',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single',
      type: FurnitureType.vanity,
      label: 'Vanity single',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.8,
      description: 'Single sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_double',
      type: FurnitureType.vanity,
      label: 'Vanity double',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 5.5,
      defaultLengthFt: 1.8,
      description: 'Double sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'bath_cabinet',
      type: FurnitureType.wardrobe,
      label: 'Bath cabinet',
      category: FurnitureCategory.bathroom,
      icon: Icons.inventory_2,
      defaultWidthFt: 2.0,
      defaultLengthFt: 1.2,
      description: 'Linen cabinet',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp',
      type: FurnitureType.lamp,
      label: 'Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 1.2,
      defaultLengthFt: 1.2,
      description: 'Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'table_lamp',
      type: FurnitureType.lamp,
      label: 'Table lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.lightbulb,
      defaultWidthFt: 1.0,
      defaultLengthFt: 1.0,
      description: 'Bedside lamp footprint',
    ),
    FurnitureCatalogEntry(
      id: 'pendant_mark',
      type: FurnitureType.lamp,
      label: 'Pendant zone',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 2.0,
      defaultLengthFt: 2.0,
      description: 'Ceiling pendant mark',
    ),
    FurnitureCatalogEntry(
      id: 'floor_mirror',
      type: FurnitureType.bookshelf,
      label: 'Floor mirror',
      category: FurnitureCategory.decor,
      icon: Icons.crop_portrait,
      defaultWidthFt: 2.0,
      defaultLengthFt: 0.8,
      description: 'Leaning / floor mirror',
    ),
    FurnitureCatalogEntry(
      id: 'plant_stand',
      type: FurnitureType.plant,
      label: 'Plant stand',
      category: FurnitureCategory.decor,
      icon: Icons.local_florist,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Plant / pedestal',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large',
      type: FurnitureType.plant,
      label: 'Large plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'plant_pair',
      type: FurnitureType.plant,
      label: 'Plant pair',
      category: FurnitureCategory.decor,
      icon: Icons.local_florist,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Pair of planters',
    ),
    FurnitureCatalogEntry(
      id: 'art_console',
      type: FurnitureType.table,
      label: 'Art console',
      category: FurnitureCategory.decor,
      icon: Icons.palette,
      defaultWidthFt: 3.5,
      defaultLengthFt: 1.2,
      description: 'Display console',
    ),
    FurnitureCatalogEntry(
      id: 'laundry_hamper',
      type: FurnitureType.nightstand,
      label: 'Laundry hamper',
      category: FurnitureCategory.decor,
      icon: Icons.local_laundry_service,
      defaultWidthFt: 1.8,
      defaultLengthFt: 1.8,
      description: 'Hamper footprint',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area',
      type: FurnitureType.rug,
      label: 'Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 8.0,
      defaultLengthFt: 5.0,
      description: 'Living area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_runner',
      type: FurnitureType.rug,
      label: 'Runner rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 8.0,
      defaultLengthFt: 2.5,
      description: 'Hall runner',
    ),
    FurnitureCatalogEntry(
      id: 'rug_round',
      type: FurnitureType.rug,
      label: 'Round rug',
      category: FurnitureCategory.decor,
      icon: Icons.circle,
      defaultWidthFt: 6.0,
      defaultLengthFt: 6.0,
      description: 'Round area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_bedroom',
      type: FurnitureType.rug,
      label: 'Bedroom rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 7.0,
      defaultLengthFt: 5.0,
      description: 'Under-bed rug',
    ),
    FurnitureCatalogEntry(
      id: 'patio_sofa',
      type: FurnitureType.outdoor,
      label: 'Patio sofa',
      category: FurnitureCategory.outdoor,
      icon: Icons.weekend,
      defaultWidthFt: 6.0,
      defaultLengthFt: 3.0,
      description: 'Outdoor sofa',
    ),
    FurnitureCatalogEntry(
      id: 'lounge_chair',
      type: FurnitureType.outdoor,
      label: 'Lounge chair',
      category: FurnitureCategory.outdoor,
      icon: Icons.beach_access,
      defaultWidthFt: 2.5,
      defaultLengthFt: 5.5,
      description: 'Pool lounge',
    ),
    FurnitureCatalogEntry(
      id: 'grill',
      type: FurnitureType.outdoor,
      label: 'BBQ grill',
      category: FurnitureCategory.outdoor,
      icon: Icons.outdoor_grill,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.0,
      description: 'Outdoor grill',
    ),
    FurnitureCatalogEntry(
      id: 'umbrella_table',
      type: FurnitureType.outdoor,
      label: 'Umbrella table',
      category: FurnitureCategory.outdoor,
      icon: Icons.table_restaurant,
      defaultWidthFt: 4.0,
      defaultLengthFt: 4.0,
      description: 'Patio table + umbrella',
    ),
    FurnitureCatalogEntry(
      id: 'planter_box',
      type: FurnitureType.plant,
      label: 'Planter box',
      category: FurnitureCategory.outdoor,
      icon: Icons.grass,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.5,
      description: 'Garden planter',
    ),
    FurnitureCatalogEntry(
      id: 'whiteboard',
      type: FurnitureType.bookshelf,
      label: 'Whiteboard wall',
      category: FurnitureCategory.office,
      icon: Icons.dashboard,
      defaultWidthFt: 4.0,
      defaultLengthFt: 0.5,
      description: 'Wall whiteboard mark',
    ),
    FurnitureCatalogEntry(
      id: 'printer_stand',
      type: FurnitureType.table,
      label: 'Printer stand',
      category: FurnitureCategory.office,
      icon: Icons.print,
      defaultWidthFt: 2.0,
      defaultLengthFt: 1.8,
      description: 'Printer / office cart',
    ),
    FurnitureCatalogEntry(
      id: 'meeting_table',
      type: FurnitureType.table,
      label: 'Meeting table',
      category: FurnitureCategory.office,
      icon: Icons.table_restaurant,
      defaultWidthFt: 6.0,
      defaultLengthFt: 3.5,
      description: 'Small conference table',
    ),
    FurnitureCatalogEntry(
      id: 'lounge_pod',
      type: FurnitureType.sofa,
      label: 'Lounge pod',
      category: FurnitureCategory.office,
      icon: Icons.weekend,
      defaultWidthFt: 4.0,
      defaultLengthFt: 4.0,
      description: 'Soft seating pod',
    ),

    // —— Expanded planner-scale variants (+86) ——
    FurnitureCatalogEntry(
      id: 'murphy_bed',
      type: FurnitureType.bed,
      label: 'Murphy bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 5.0,
      defaultLengthFt: 2.0,
      description: 'Wall bed closed footprint',
    ),
    FurnitureCatalogEntry(
      id: 'trundle_bed',
      type: FurnitureType.bed,
      label: 'Trundle bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 3.5,
      defaultLengthFt: 6.5,
      description: 'Daybed with trundle',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_bed',
      type: FurnitureType.sofa,
      label: 'Sofa bed',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 7.0,
      defaultLengthFt: 3.2,
      description: 'Convertible sleeper sofa',
    ),
    FurnitureCatalogEntry(
      id: 'accent_chair',
      type: FurnitureType.chair,
      label: 'Accent chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Decorative lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'bar_cart',
      type: FurnitureType.table,
      label: 'Bar cart',
      category: FurnitureCategory.tables,
      icon: Icons.local_bar,
      defaultWidthFt: 2.5,
      defaultLengthFt: 1.5,
      description: 'Mobile bar cart',
    ),
    FurnitureCatalogEntry(
      id: 'entry_console',
      type: FurnitureType.table,
      label: 'Entry console',
      category: FurnitureCategory.tables,
      icon: Icons.table_bar,
      defaultWidthFt: 4.5,
      defaultLengthFt: 1.3,
      description: 'Foyer console table',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_corner',
      type: FurnitureType.wardrobe,
      label: 'Corner wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 4.0,
      defaultLengthFt: 4.0,
      description: 'Corner closet unit',
    ),
    FurnitureCatalogEntry(
      id: 'cube_storage',
      type: FurnitureType.bookshelf,
      label: 'Cube storage',
      category: FurnitureCategory.storage,
      icon: Icons.grid_view,
      defaultWidthFt: 3.5,
      defaultLengthFt: 1.2,
      description: 'Cubbies / modular storage',
    ),
    FurnitureCatalogEntry(
      id: 'tv_wall',
      type: FurnitureType.tvUnit,
      label: 'TV wall unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 8.0,
      defaultLengthFt: 1.5,
      description: 'Full wall media system',
    ),
    FurnitureCatalogEntry(
      id: 'speaker_pair',
      type: FurnitureType.tvUnit,
      label: 'Speaker pair mark',
      category: FurnitureCategory.media,
      icon: Icons.speaker,
      defaultWidthFt: 1.0,
      defaultLengthFt: 1.0,
      description: 'Floor speaker footprint',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_french',
      type: FurnitureType.appliance,
      label: 'French-door fridge',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 3.5,
      defaultLengthFt: 2.8,
      description: 'Wide refrigerator',
    ),
    FurnitureCatalogEntry(
      id: 'sink_island',
      type: FurnitureType.appliance,
      label: 'Island sink zone',
      category: FurnitureCategory.kitchen,
      icon: Icons.countertops,
      defaultWidthFt: 3.0,
      defaultLengthFt: 2.5,
      description: 'Kitchen island sink',
    ),
    FurnitureCatalogEntry(
      id: 'washer',
      type: FurnitureType.appliance,
      label: 'Washer',
      category: FurnitureCategory.kitchen,
      icon: Icons.local_laundry_service,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Washing machine',
    ),
    FurnitureCatalogEntry(
      id: 'dryer',
      type: FurnitureType.appliance,
      label: 'Dryer',
      category: FurnitureCategory.kitchen,
      icon: Icons.local_laundry_service,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Clothes dryer',
    ),
    FurnitureCatalogEntry(
      id: 'bidet',
      type: FurnitureType.toilet,
      label: 'Bidet',
      category: FurnitureCategory.bathroom,
      icon: Icons.wc,
      defaultWidthFt: 1.5,
      defaultLengthFt: 2.2,
      description: 'Bidet footprint',
    ),
    FurnitureCatalogEntry(
      id: 'jacuzzi',
      type: FurnitureType.bathtub,
      label: 'Jacuzzi tub',
      category: FurnitureCategory.bathroom,
      icon: Icons.hot_tub,
      defaultWidthFt: 6.0,
      defaultLengthFt: 6.0,
      description: 'Corner whirlpool tub',
    ),
    FurnitureCatalogEntry(
      id: 'chandelier_mark',
      type: FurnitureType.lamp,
      label: 'Chandelier zone',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 3.0,
      defaultLengthFt: 3.0,
      description: 'Ceiling chandelier mark',
    ),
    FurnitureCatalogEntry(
      id: 'sconce_pair',
      type: FurnitureType.lamp,
      label: 'Sconce pair',
      category: FurnitureCategory.lighting,
      icon: Icons.lightbulb_outline,
      defaultWidthFt: 0.8,
      defaultLengthFt: 0.5,
      description: 'Wall sconce marks',
    ),
    FurnitureCatalogEntry(
      id: 'floor_vase',
      type: FurnitureType.plant,
      label: 'Floor vase',
      category: FurnitureCategory.decor,
      icon: Icons.local_florist,
      defaultWidthFt: 1.2,
      defaultLengthFt: 1.2,
      description: 'Decorative floor vase',
    ),
    FurnitureCatalogEntry(
      id: 'fireplace',
      type: FurnitureType.outdoor,
      label: 'Fireplace mark',
      category: FurnitureCategory.decor,
      icon: Icons.fireplace,
      defaultWidthFt: 5.0,
      defaultLengthFt: 1.5,
      description: 'Fireplace wall unit',
    ),
    FurnitureCatalogEntry(
      id: 'piano',
      type: FurnitureType.table,
      label: 'Upright piano',
      category: FurnitureCategory.decor,
      icon: Icons.piano,
      defaultWidthFt: 5.0,
      defaultLengthFt: 2.0,
      description: 'Upright piano footprint',
    ),
    FurnitureCatalogEntry(
      id: 'treadmill',
      type: FurnitureType.outdoor,
      label: 'Treadmill',
      category: FurnitureCategory.office,
      icon: Icons.directions_run,
      defaultWidthFt: 3.0,
      defaultLengthFt: 6.0,
      description: 'Home gym treadmill',
    ),
    FurnitureCatalogEntry(
      id: 'yoga_mat_zone',
      type: FurnitureType.rug,
      label: 'Yoga mat zone',
      category: FurnitureCategory.office,
      icon: Icons.self_improvement,
      defaultWidthFt: 6.0,
      defaultLengthFt: 2.5,
      description: 'Exercise mat area',
    ),
    FurnitureCatalogEntry(
      id: 'bike_trainer',
      type: FurnitureType.outdoor,
      label: 'Exercise bike',
      category: FurnitureCategory.office,
      icon: Icons.pedal_bike,
      defaultWidthFt: 2.0,
      defaultLengthFt: 4.0,
      description: 'Stationary bike',
    ),
    FurnitureCatalogEntry(
      id: 'patio_dining',
      type: FurnitureType.outdoor,
      label: 'Patio dining set',
      category: FurnitureCategory.outdoor,
      icon: Icons.table_restaurant,
      defaultWidthFt: 5.0,
      defaultLengthFt: 5.0,
      description: 'Outdoor dining footprint',
    ),
    FurnitureCatalogEntry(
      id: 'hammock',
      type: FurnitureType.outdoor,
      label: 'Hammock zone',
      category: FurnitureCategory.outdoor,
      icon: Icons.beach_access,
      defaultWidthFt: 8.0,
      defaultLengthFt: 4.0,
      description: 'Hammock swing area',
    ),
    // —— Procedural size/finish variants (+87) ——
    FurnitureCatalogEntry(
      id: 'queen_bed_xs',
      type: FurnitureType.bed,
      label: 'Compact Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 3.75,
      defaultLengthFt: 5.03,
      description: 'Compact Queen mattress',
    ),
    FurnitureCatalogEntry(
      id: 'queen_bed_sm',
      type: FurnitureType.bed,
      label: 'Small Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 4.5,
      defaultLengthFt: 6.03,
      description: 'Small Queen mattress',
    ),
    FurnitureCatalogEntry(
      id: 'queen_bed_lg',
      type: FurnitureType.bed,
      label: 'Large Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 5.75,
      defaultLengthFt: 7.7,
      description: 'Large Queen mattress',
    ),
    FurnitureCatalogEntry(
      id: 'queen_bed_xl',
      type: FurnitureType.bed,
      label: 'XL Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 6.5,
      defaultLengthFt: 8.71,
      description: 'XL Queen mattress',
    ),
    FurnitureCatalogEntry(
      id: 'queen_bed_modern',
      type: FurnitureType.bed,
      label: 'Modern Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 5.0,
      defaultLengthFt: 6.7,
      description: 'Modern finish · Queen mattress',
    ),
    FurnitureCatalogEntry(
      id: 'queen_bed_classic',
      type: FurnitureType.bed,
      label: 'Classic Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 5.0,
      defaultLengthFt: 6.7,
      description: 'Classic finish · Queen mattress',
    ),
    FurnitureCatalogEntry(
      id: 'queen_bed_oak',
      type: FurnitureType.bed,
      label: 'Oak Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 5.0,
      defaultLengthFt: 6.7,
      description: 'Oak finish · Queen mattress',
    ),
    FurnitureCatalogEntry(
      id: 'queen_bed_walnut',
      type: FurnitureType.bed,
      label: 'Walnut Queen bed',
      category: FurnitureCategory.sleep,
      icon: Icons.bed,
      defaultWidthFt: 5.0,
      defaultLengthFt: 6.7,
      description: 'Walnut finish · Queen mattress',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3_xs',
      type: FurnitureType.sofa,
      label: 'Compact Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 5.25,
      defaultLengthFt: 2.25,
      description: 'Compact Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3_sm',
      type: FurnitureType.sofa,
      label: 'Small Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 6.3,
      defaultLengthFt: 2.7,
      description: 'Small Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3_lg',
      type: FurnitureType.sofa,
      label: 'Large Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 8.05,
      defaultLengthFt: 3.45,
      description: 'Large Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3_xl',
      type: FurnitureType.sofa,
      label: 'XL Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 9.1,
      defaultLengthFt: 3.9,
      description: 'XL Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3_modern',
      type: FurnitureType.sofa,
      label: 'Modern Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 7.0,
      defaultLengthFt: 3.0,
      description: 'Modern finish · Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3_classic',
      type: FurnitureType.sofa,
      label: 'Classic Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 7.0,
      defaultLengthFt: 3.0,
      description: 'Classic finish · Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3_oak',
      type: FurnitureType.sofa,
      label: 'Oak Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 7.0,
      defaultLengthFt: 3.0,
      description: 'Oak finish · Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'sofa_3_walnut',
      type: FurnitureType.sofa,
      label: 'Walnut Sofa 3-seat',
      category: FurnitureCategory.seating,
      icon: Icons.weekend,
      defaultWidthFt: 7.0,
      defaultLengthFt: 3.0,
      description: 'Walnut finish · Standard sofa',
    ),
    FurnitureCatalogEntry(
      id: 'desk_xs',
      type: FurnitureType.desk,
      label: 'Compact Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 3.38,
      defaultLengthFt: 1.65,
      description: 'Compact Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_sm',
      type: FurnitureType.desk,
      label: 'Small Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 4.05,
      defaultLengthFt: 1.98,
      description: 'Small Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_lg',
      type: FurnitureType.desk,
      label: 'Large Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 5.17,
      defaultLengthFt: 2.53,
      description: 'Large Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_xl',
      type: FurnitureType.desk,
      label: 'XL Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 5.85,
      defaultLengthFt: 2.86,
      description: 'XL Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_modern',
      type: FurnitureType.desk,
      label: 'Modern Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 4.5,
      defaultLengthFt: 2.2,
      description: 'Modern finish · Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_classic',
      type: FurnitureType.desk,
      label: 'Classic Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 4.5,
      defaultLengthFt: 2.2,
      description: 'Classic finish · Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_oak',
      type: FurnitureType.desk,
      label: 'Oak Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 4.5,
      defaultLengthFt: 2.2,
      description: 'Oak finish · Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'desk_walnut',
      type: FurnitureType.desk,
      label: 'Walnut Desk',
      category: FurnitureCategory.tables,
      icon: Icons.desktop_windows,
      defaultWidthFt: 4.5,
      defaultLengthFt: 2.2,
      description: 'Walnut finish · Work desk',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_xs',
      type: FurnitureType.wardrobe,
      label: 'Compact Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 4.88,
      defaultLengthFt: 1.12,
      description: 'Compact Sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_sm',
      type: FurnitureType.wardrobe,
      label: 'Small Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 5.85,
      defaultLengthFt: 1.35,
      description: 'Small Sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_lg',
      type: FurnitureType.wardrobe,
      label: 'Large Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 7.47,
      defaultLengthFt: 1.72,
      description: 'Large Sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_xl',
      type: FurnitureType.wardrobe,
      label: 'XL Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 8.45,
      defaultLengthFt: 1.95,
      description: 'XL Sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_modern',
      type: FurnitureType.wardrobe,
      label: 'Modern Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 6.5,
      defaultLengthFt: 1.5,
      description: 'Modern finish · Sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_classic',
      type: FurnitureType.wardrobe,
      label: 'Classic Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 6.5,
      defaultLengthFt: 1.5,
      description: 'Classic finish · Sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_oak',
      type: FurnitureType.wardrobe,
      label: 'Oak Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 6.5,
      defaultLengthFt: 1.5,
      description: 'Oak finish · Sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'wardrobe_walnut',
      type: FurnitureType.wardrobe,
      label: 'Walnut Wardrobe',
      category: FurnitureCategory.storage,
      icon: Icons.door_sliding,
      defaultWidthFt: 6.5,
      defaultLengthFt: 1.5,
      description: 'Walnut finish · Sliding wardrobe',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_xs',
      type: FurnitureType.bookshelf,
      label: 'Compact Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 2.25,
      defaultLengthFt: 0.75,
      description: 'Compact Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_sm',
      type: FurnitureType.bookshelf,
      label: 'Small Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 2.7,
      defaultLengthFt: 0.9,
      description: 'Small Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_lg',
      type: FurnitureType.bookshelf,
      label: 'Large Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 3.45,
      defaultLengthFt: 1.15,
      description: 'Large Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_xl',
      type: FurnitureType.bookshelf,
      label: 'XL Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 3.9,
      defaultLengthFt: 1.3,
      description: 'XL Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_modern',
      type: FurnitureType.bookshelf,
      label: 'Modern Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.0,
      description: 'Modern finish · Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_classic',
      type: FurnitureType.bookshelf,
      label: 'Classic Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.0,
      description: 'Classic finish · Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_oak',
      type: FurnitureType.bookshelf,
      label: 'Oak Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.0,
      description: 'Oak finish · Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'bookshelf_walnut',
      type: FurnitureType.bookshelf,
      label: 'Walnut Bookshelf',
      category: FurnitureCategory.storage,
      icon: Icons.menu_book,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.0,
      description: 'Walnut finish · Bookcase',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_xs',
      type: FurnitureType.tvUnit,
      label: 'Compact TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 3.75,
      defaultLengthFt: 1.12,
      description: 'Compact Media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_sm',
      type: FurnitureType.tvUnit,
      label: 'Small TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 4.5,
      defaultLengthFt: 1.35,
      description: 'Small Media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_lg',
      type: FurnitureType.tvUnit,
      label: 'Large TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 5.75,
      defaultLengthFt: 1.72,
      description: 'Large Media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_xl',
      type: FurnitureType.tvUnit,
      label: 'XL TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 6.5,
      defaultLengthFt: 1.95,
      description: 'XL Media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_modern',
      type: FurnitureType.tvUnit,
      label: 'Modern TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 5.0,
      defaultLengthFt: 1.5,
      description: 'Modern finish · Media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_classic',
      type: FurnitureType.tvUnit,
      label: 'Classic TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 5.0,
      defaultLengthFt: 1.5,
      description: 'Classic finish · Media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_oak',
      type: FurnitureType.tvUnit,
      label: 'Oak TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 5.0,
      defaultLengthFt: 1.5,
      description: 'Oak finish · Media console',
    ),
    FurnitureCatalogEntry(
      id: 'tv_unit_walnut',
      type: FurnitureType.tvUnit,
      label: 'Walnut TV unit',
      category: FurnitureCategory.media,
      icon: Icons.tv,
      defaultWidthFt: 5.0,
      defaultLengthFt: 1.5,
      description: 'Walnut finish · Media console',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4_xs',
      type: FurnitureType.table,
      label: 'Compact Dining table',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 3.0,
      defaultLengthFt: 2.25,
      description: 'Compact Dining table',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4_sm',
      type: FurnitureType.table,
      label: 'Small Dining table',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 3.6,
      defaultLengthFt: 2.7,
      description: 'Small Dining table',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4_lg',
      type: FurnitureType.table,
      label: 'Large Dining table',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 4.6,
      defaultLengthFt: 3.45,
      description: 'Large Dining table',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4_xl',
      type: FurnitureType.table,
      label: 'XL Dining table',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 5.2,
      defaultLengthFt: 3.9,
      description: 'XL Dining table',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4_modern',
      type: FurnitureType.table,
      label: 'Modern Dining table',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 4.0,
      defaultLengthFt: 3.0,
      description: 'Modern finish · Dining table',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4_classic',
      type: FurnitureType.table,
      label: 'Classic Dining table',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 4.0,
      defaultLengthFt: 3.0,
      description: 'Classic finish · Dining table',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4_oak',
      type: FurnitureType.table,
      label: 'Oak Dining table',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 4.0,
      defaultLengthFt: 3.0,
      description: 'Oak finish · Dining table',
    ),
    FurnitureCatalogEntry(
      id: 'dining_table_4_walnut',
      type: FurnitureType.table,
      label: 'Walnut Dining table',
      category: FurnitureCategory.tables,
      icon: Icons.table_restaurant,
      defaultWidthFt: 4.0,
      defaultLengthFt: 3.0,
      description: 'Walnut finish · Dining table',
    ),
    FurnitureCatalogEntry(
      id: 'armchair_xs',
      type: FurnitureType.chair,
      label: 'Compact Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 2.1,
      defaultLengthFt: 2.1,
      description: 'Compact Lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'armchair_sm',
      type: FurnitureType.chair,
      label: 'Small Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 2.52,
      defaultLengthFt: 2.52,
      description: 'Small Lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'armchair_lg',
      type: FurnitureType.chair,
      label: 'Large Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 3.22,
      defaultLengthFt: 3.22,
      description: 'Large Lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'armchair_xl',
      type: FurnitureType.chair,
      label: 'XL Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 3.64,
      defaultLengthFt: 3.64,
      description: 'XL Lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'armchair_modern',
      type: FurnitureType.chair,
      label: 'Modern Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 2.8,
      defaultLengthFt: 2.8,
      description: 'Modern finish · Lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'armchair_classic',
      type: FurnitureType.chair,
      label: 'Classic Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 2.8,
      defaultLengthFt: 2.8,
      description: 'Classic finish · Lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'armchair_oak',
      type: FurnitureType.chair,
      label: 'Oak Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 2.8,
      defaultLengthFt: 2.8,
      description: 'Oak finish · Lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'armchair_walnut',
      type: FurnitureType.chair,
      label: 'Walnut Armchair',
      category: FurnitureCategory.seating,
      icon: Icons.chair,
      defaultWidthFt: 2.8,
      defaultLengthFt: 2.8,
      description: 'Walnut finish · Lounge chair',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large_xs',
      type: FurnitureType.plant,
      label: 'Compact Plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 1.88,
      defaultLengthFt: 1.88,
      description: 'Compact Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large_sm',
      type: FurnitureType.plant,
      label: 'Small Plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 2.25,
      defaultLengthFt: 2.25,
      description: 'Small Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large_lg',
      type: FurnitureType.plant,
      label: 'Large Plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 2.88,
      defaultLengthFt: 2.88,
      description: 'Large Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large_xl',
      type: FurnitureType.plant,
      label: 'XL Plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 3.25,
      defaultLengthFt: 3.25,
      description: 'XL Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large_modern',
      type: FurnitureType.plant,
      label: 'Modern Plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Modern finish · Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large_classic',
      type: FurnitureType.plant,
      label: 'Classic Plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Classic finish · Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large_oak',
      type: FurnitureType.plant,
      label: 'Oak Plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Oak finish · Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'plant_large_walnut',
      type: FurnitureType.plant,
      label: 'Walnut Plant',
      category: FurnitureCategory.decor,
      icon: Icons.park,
      defaultWidthFt: 2.5,
      defaultLengthFt: 2.5,
      description: 'Walnut finish · Floor plant',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp_xs',
      type: FurnitureType.lamp,
      label: 'Compact Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 0.9,
      defaultLengthFt: 0.9,
      description: 'Compact Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp_sm',
      type: FurnitureType.lamp,
      label: 'Small Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 1.08,
      defaultLengthFt: 1.08,
      description: 'Small Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp_lg',
      type: FurnitureType.lamp,
      label: 'Large Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 1.38,
      defaultLengthFt: 1.38,
      description: 'Large Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp_xl',
      type: FurnitureType.lamp,
      label: 'XL Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 1.56,
      defaultLengthFt: 1.56,
      description: 'XL Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp_modern',
      type: FurnitureType.lamp,
      label: 'Modern Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 1.2,
      defaultLengthFt: 1.2,
      description: 'Modern finish · Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp_classic',
      type: FurnitureType.lamp,
      label: 'Classic Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 1.2,
      defaultLengthFt: 1.2,
      description: 'Classic finish · Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp_oak',
      type: FurnitureType.lamp,
      label: 'Oak Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 1.2,
      defaultLengthFt: 1.2,
      description: 'Oak finish · Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'floor_lamp_walnut',
      type: FurnitureType.lamp,
      label: 'Walnut Floor lamp',
      category: FurnitureCategory.lighting,
      icon: Icons.light,
      defaultWidthFt: 1.2,
      defaultLengthFt: 1.2,
      description: 'Walnut finish · Standing lamp',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area_xs',
      type: FurnitureType.rug,
      label: 'Compact Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 6.0,
      defaultLengthFt: 3.75,
      description: 'Compact Area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area_sm',
      type: FurnitureType.rug,
      label: 'Small Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 7.2,
      defaultLengthFt: 4.5,
      description: 'Small Area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area_lg',
      type: FurnitureType.rug,
      label: 'Large Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 9.2,
      defaultLengthFt: 5.75,
      description: 'Large Area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area_xl',
      type: FurnitureType.rug,
      label: 'XL Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 10.4,
      defaultLengthFt: 6.5,
      description: 'XL Area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area_modern',
      type: FurnitureType.rug,
      label: 'Modern Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 8.0,
      defaultLengthFt: 5.0,
      description: 'Modern finish · Area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area_classic',
      type: FurnitureType.rug,
      label: 'Classic Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 8.0,
      defaultLengthFt: 5.0,
      description: 'Classic finish · Area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area_oak',
      type: FurnitureType.rug,
      label: 'Oak Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 8.0,
      defaultLengthFt: 5.0,
      description: 'Oak finish · Area rug',
    ),
    FurnitureCatalogEntry(
      id: 'rug_area_walnut',
      type: FurnitureType.rug,
      label: 'Walnut Area rug',
      category: FurnitureCategory.decor,
      icon: Icons.crop_landscape,
      defaultWidthFt: 8.0,
      defaultLengthFt: 5.0,
      description: 'Walnut finish · Area rug',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_xs',
      type: FurnitureType.appliance,
      label: 'Compact Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 2.25,
      defaultLengthFt: 2.1,
      description: 'Compact Fridge',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_sm',
      type: FurnitureType.appliance,
      label: 'Small Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 2.7,
      defaultLengthFt: 2.52,
      description: 'Small Fridge',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_lg',
      type: FurnitureType.appliance,
      label: 'Large Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 3.45,
      defaultLengthFt: 3.22,
      description: 'Large Fridge',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_xl',
      type: FurnitureType.appliance,
      label: 'XL Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 3.9,
      defaultLengthFt: 3.64,
      description: 'XL Fridge',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_modern',
      type: FurnitureType.appliance,
      label: 'Modern Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 3.0,
      defaultLengthFt: 2.8,
      description: 'Modern finish · Fridge',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_classic',
      type: FurnitureType.appliance,
      label: 'Classic Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 3.0,
      defaultLengthFt: 2.8,
      description: 'Classic finish · Fridge',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_oak',
      type: FurnitureType.appliance,
      label: 'Oak Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 3.0,
      defaultLengthFt: 2.8,
      description: 'Oak finish · Fridge',
    ),
    FurnitureCatalogEntry(
      id: 'fridge_walnut',
      type: FurnitureType.appliance,
      label: 'Walnut Refrigerator',
      category: FurnitureCategory.kitchen,
      icon: Icons.kitchen,
      defaultWidthFt: 3.0,
      defaultLengthFt: 2.8,
      description: 'Walnut finish · Fridge',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub_xs',
      type: FurnitureType.bathtub,
      label: 'Compact Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 3.75,
      defaultLengthFt: 2.1,
      description: 'Compact Tub',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub_sm',
      type: FurnitureType.bathtub,
      label: 'Small Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 4.5,
      defaultLengthFt: 2.52,
      description: 'Small Tub',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub_lg',
      type: FurnitureType.bathtub,
      label: 'Large Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 5.75,
      defaultLengthFt: 3.22,
      description: 'Large Tub',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub_xl',
      type: FurnitureType.bathtub,
      label: 'XL Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 6.5,
      defaultLengthFt: 3.64,
      description: 'XL Tub',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub_modern',
      type: FurnitureType.bathtub,
      label: 'Modern Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 5.0,
      defaultLengthFt: 2.8,
      description: 'Modern finish · Tub',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub_classic',
      type: FurnitureType.bathtub,
      label: 'Classic Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 5.0,
      defaultLengthFt: 2.8,
      description: 'Classic finish · Tub',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub_oak',
      type: FurnitureType.bathtub,
      label: 'Oak Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 5.0,
      defaultLengthFt: 2.8,
      description: 'Oak finish · Tub',
    ),
    FurnitureCatalogEntry(
      id: 'bathtub_walnut',
      type: FurnitureType.bathtub,
      label: 'Walnut Bathtub',
      category: FurnitureCategory.bathroom,
      icon: Icons.bathtub,
      defaultWidthFt: 5.0,
      defaultLengthFt: 2.8,
      description: 'Walnut finish · Tub',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single_xs',
      type: FurnitureType.vanity,
      label: 'Compact Vanity',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 2.25,
      defaultLengthFt: 1.35,
      description: 'Compact Sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single_sm',
      type: FurnitureType.vanity,
      label: 'Small Vanity',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 2.7,
      defaultLengthFt: 1.62,
      description: 'Small Sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single_lg',
      type: FurnitureType.vanity,
      label: 'Large Vanity',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 3.45,
      defaultLengthFt: 2.07,
      description: 'Large Sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single_xl',
      type: FurnitureType.vanity,
      label: 'XL Vanity',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 3.9,
      defaultLengthFt: 2.34,
      description: 'XL Sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single_modern',
      type: FurnitureType.vanity,
      label: 'Modern Vanity',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.8,
      description: 'Modern finish · Sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single_classic',
      type: FurnitureType.vanity,
      label: 'Classic Vanity',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.8,
      description: 'Classic finish · Sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single_oak',
      type: FurnitureType.vanity,
      label: 'Oak Vanity',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.8,
      description: 'Oak finish · Sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'vanity_single_walnut',
      type: FurnitureType.vanity,
      label: 'Walnut Vanity',
      category: FurnitureCategory.bathroom,
      icon: Icons.wash,
      defaultWidthFt: 3.0,
      defaultLengthFt: 1.8,
      description: 'Walnut finish · Sink vanity',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_xs',
      type: FurnitureType.nightstand,
      label: 'Compact Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.12,
      defaultLengthFt: 1.12,
      description: 'Compact Bedside',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_sm',
      type: FurnitureType.nightstand,
      label: 'Small Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.35,
      defaultLengthFt: 1.35,
      description: 'Small Bedside',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_lg',
      type: FurnitureType.nightstand,
      label: 'Large Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.72,
      defaultLengthFt: 1.72,
      description: 'Large Bedside',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_xl',
      type: FurnitureType.nightstand,
      label: 'XL Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.95,
      defaultLengthFt: 1.95,
      description: 'XL Bedside',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_modern',
      type: FurnitureType.nightstand,
      label: 'Modern Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Modern finish · Bedside',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_classic',
      type: FurnitureType.nightstand,
      label: 'Classic Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Classic finish · Bedside',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_oak',
      type: FurnitureType.nightstand,
      label: 'Oak Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Oak finish · Bedside',
    ),
    FurnitureCatalogEntry(
      id: 'nightstand_walnut',
      type: FurnitureType.nightstand,
      label: 'Walnut Nightstand',
      category: FurnitureCategory.sleep,
      icon: Icons.table_restaurant,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Walnut finish · Bedside',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair_xs',
      type: FurnitureType.chair,
      label: 'Compact Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 1.5,
      defaultLengthFt: 1.5,
      description: 'Compact Desk chair',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair_sm',
      type: FurnitureType.chair,
      label: 'Small Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 1.8,
      defaultLengthFt: 1.8,
      description: 'Small Desk chair',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair_lg',
      type: FurnitureType.chair,
      label: 'Large Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 2.3,
      defaultLengthFt: 2.3,
      description: 'Large Desk chair',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair_xl',
      type: FurnitureType.chair,
      label: 'XL Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 2.6,
      defaultLengthFt: 2.6,
      description: 'XL Desk chair',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair_modern',
      type: FurnitureType.chair,
      label: 'Modern Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 2.0,
      defaultLengthFt: 2.0,
      description: 'Modern finish · Desk chair',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair_classic',
      type: FurnitureType.chair,
      label: 'Classic Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 2.0,
      defaultLengthFt: 2.0,
      description: 'Classic finish · Desk chair',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair_oak',
      type: FurnitureType.chair,
      label: 'Oak Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 2.0,
      defaultLengthFt: 2.0,
      description: 'Oak finish · Desk chair',
    ),
    FurnitureCatalogEntry(
      id: 'office_chair_walnut',
      type: FurnitureType.chair,
      label: 'Walnut Office chair',
      category: FurnitureCategory.seating,
      icon: Icons.chair_alt,
      defaultWidthFt: 2.0,
      defaultLengthFt: 2.0,
      description: 'Walnut finish · Desk chair',
    ),

  ];

  static int get count => all.length;

  static FurnitureCatalogEntry entryFor(FurnitureType type) {
    return all.firstWhere(
      (e) => e.type == type,
      orElse: () => all.first,
    );
  }

  static FurnitureCatalogEntry entryForSized(
    FurnitureType type, {
    double? widthFt,
    double? lengthFt,
  }) {
    if (type == FurnitureType.wardrobe) {
      final long = mathMax(widthFt ?? 0, lengthFt ?? 0);
      if (long >= 5.5) {
        return byId('wardrobe_wide') ?? entryFor(type);
      }
    }
    return entryFor(type);
  }

  static double mathMax(double a, double b) => a > b ? a : b;

  static FurnitureCatalogEntry? byId(String id) {
    try {
      return all.firstWhere((e) => e.id == id);
    } catch (_) {
      return null;
    }
  }

  static List<FurnitureCatalogEntry> byCategory(FurnitureCategory c) {
    return all.where((e) => e.category == c).toList();
  }

  static List<FurnitureCatalogEntry> search(String query) {
    final q = query.trim().toLowerCase();
    if (q.isEmpty) return all;
    return all.where((e) {
      return e.label.toLowerCase().contains(q) ||
          e.description.toLowerCase().contains(q) ||
          e.id.contains(q) ||
          e.type.name.toLowerCase().contains(q) ||
          categoryLabel(e.category).toLowerCase().contains(q);
    }).toList();
  }

  static String categoryLabel(FurnitureCategory c) {
    switch (c) {
      case FurnitureCategory.sleep:
        return 'Sleep';
      case FurnitureCategory.seating:
        return 'Seating';
      case FurnitureCategory.tables:
        return 'Tables';
      case FurnitureCategory.storage:
        return 'Storage';
      case FurnitureCategory.media:
        return 'Media';
      case FurnitureCategory.kitchen:
        return 'Kitchen';
      case FurnitureCategory.bathroom:
        return 'Bathroom';
      case FurnitureCategory.lighting:
        return 'Lighting';
      case FurnitureCategory.decor:
        return 'Decor';
      case FurnitureCategory.outdoor:
        return 'Outdoor';
      case FurnitureCategory.office:
        return 'Office';
    }
  }
}
